# Generated by Django 5.0.1 on 2024-01-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('account_created', 'Account Created'), ('login', 'Login'), ('file_upload', 'File Upload'), ('delete_space', 'Delete Space'), ('file_report_submitted', 'Report Submitted'), ('file_report_change', 'Report Change'), ('invalid_space_password', 'Invalid ShareSpace Password Provided')], max_length=50),
        ),
    ]
