# Generated by Django 5.0.1 on 2024-01-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('account_created', 'Account Created'), ('login', 'Login'), ('file_upload', 'File Upload'), ('delete_space', 'Delete Space'), ('file_report_submitted', 'File Report Submitted'), ('file_report_change', 'File Report Change'), ('space_report_submitted', 'ShareSpace Report Submitted'), ('space_report_change', 'Space Report Change'), ('invalid_space_password', 'Invalid ShareSpace Password Provided')], max_length=50),
        ),
    ]
