# Generated by Django 5.0 on 2023-12-18 16:21

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_fileupload_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='id',
            field=models.CharField(default=app.models.generate_unique_id, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
