# Generated by Django 5.0 on 2023-12-20 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_uploadedfile_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('file_reported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.uploadedfile')),
                ('reported_by', models.ManyToManyField(related_name='reports_sent', to=settings.AUTH_USER_MODEL)),
                ('user_reported', models.ManyToManyField(related_name='reports_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
