# Generated by Django 5.0 on 2023-12-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_uploadedfile_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('UR', 'Under Review'), ('RNA', 'Reviewed - No Action Taken'), ('RAT', 'Reviewed - Action Taken')], default='UR', max_length=3),
        ),
    ]
