# Generated by Django 5.0.1 on 2024-01-02 15:35

import app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_report_reviewed_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='title',
        ),
        migrations.CreateModel(
            name='ShareSpace',
            fields=[
                ('id', models.CharField(default=app.models.generate_unique_id, editable=False, max_length=8, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='share_space',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app.sharespace'),
            preserve_default=False,
        ),
    ]
