# Generated by Django 5.0.1 on 2024-01-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_uploadedfile_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('UR', 'Under Review'), ('RNA', 'No Action Taken'), ('RAT', 'Action Taken')], default='UR', max_length=3),
        ),
    ]
