# Generated by Django 5.0.1 on 2024-01-05 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_report_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sharespace',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sharespace',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('password_protected', 'Password Protected'), ('private', 'Private')], default='private', max_length=20),
        ),
        migrations.AlterField(
            model_name='sharespace',
            name='title',
            field=models.CharField(max_length=64),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='app.sharespace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
