# Generated by Django 5.0.1 on 2024-01-08 15:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_sharespaceaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
